name: Reusable - Test Python

on:
  workflow_call:
    inputs:
      runner:
        type: string
        default: pi-arm64
      working-directory:
        description: "Directory to run in (for monorepos). Default = repo root."
        type: string
        default: "."
      uv-sync-args:
        type: string
        default: ""
      test-path:
        type: string
        default: tests/

jobs:
  test:
    runs-on: ${{ inputs.runner }}
    steps:
      - uses: actions/checkout@v7.0.0
      - uses: astral-sh/setup-uv@v8.2.0
      - run: uv sync ${{ inputs.uv-sync-args }}
        working-directory: ${{ inputs.working-directory }}
      - run: uv run pytest ${{ inputs.test-path }} -v
        working-directory: ${{ inputs.working-directory }}
